"""Add bg_gradient to Event

Revision ID: 68ea7f921403
Revises: 6df0eaf0847a
Create Date: 2025-05-19 17:17:39.993243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ea7f921403'
down_revision = '6df0eaf0847a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bg_gradient', sa.String(length=200), nullable=True))
        batch_op.drop_column('background')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('bg_gradient')

    # ### end Alembic commands ###
