"""Add background field to Event

Revision ID: 6df0eaf0847a
Revises: 2e46fe4a39d1
Create Date: 2025-05-19 16:33:27.717658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df0eaf0847a'
down_revision = '2e46fe4a39d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('background')

    # ### end Alembic commands ###
