"""Add event_participants table

Revision ID: f2cbefa70469
Revises: 
Create Date: 2025-05-15 00:27:23.723935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2cbefa70469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mmu_buildings', schema=None) as batch_op:
        batch_op.drop_column('location_coord')
        batch_op.drop_column('description')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('room_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('building_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('mmu_buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_coord', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
